/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.una.citasmedicas.view;

import com.una.citasmedicas.view.Pacientes.FrmAgregarPaciente;
import com.una.citasmedicas.view.Pacientes.FrmBuscarPaciente;
import com.una.citasmedicas.view.Pacientes.FrmDeletePaciente;
import com.una.citasmedicas.view.Pacientes.FrmModificarPaciente;
import com.una.citasmedicas.view.Pacientes.FrmPaciente;

import com.una.citasmedicas.view.medicos.FrmAgregarMedico;
import com.una.citasmedicas.view.medicos.FrmBuscarMedico;
import com.una.citasmedicas.view.medicos.FrmEliminarMedico;
import com.una.citasmedicas.view.medicos.FrmMedico;
import com.una.citasmedicas.view.medicos.FrmModificarMedico;

import com.una.citasmedicas.view.usuarios.FrmAgregarUsuario;
import com.una.citasmedicas.view.usuarios.FrmEliminarUsuario;
import com.una.citasmedicas.view.usuarios.FrmJtable;
import com.una.citasmedicas.view.usuarios.FrmModificarUsuario;

/**
 *
 * @author PC
 */
public class MDIMainUI extends javax.swing.JFrame {

    
    FrmAgregarMedico frmAgregarMedico;
    FrmBuscarMedico frmBuscarMedico;
    FrmModificarMedico frmModificarMedico;
    FrmEliminarMedico frmEliminarMedico;
    FrmMedico frmMedico;
   
   
    FrmAgregarPaciente frmAgregarPaciente;
    FrmBuscarPaciente frmBuscarPaciente;
    FrmModificarPaciente frmModificarPaciente;
    FrmDeletePaciente frmEliminarPaciente;
    FrmPaciente frmPaciente;

    FrmEliminarUsuario frmEliminarUsuario;
    FrmAgregarUsuario frmAgregarUsuario;
    FrmModificarUsuario frmModificarUsuario;
    FrmJtable frmMostrarUsuario;

    /**
     * Creates new form MDIMainUI
     *
     * @throws java.lang.Exception
     */
    public MDIMainUI() throws Exception {
        frmMedico = new FrmMedico();
        frmAgregarMedico = new FrmAgregarMedico();
        frmBuscarMedico = new FrmBuscarMedico();
        frmModificarMedico = new FrmModificarMedico();
        frmEliminarMedico = new FrmEliminarMedico();

        frmAgregarPaciente = new FrmAgregarPaciente();
        frmBuscarPaciente = new FrmBuscarPaciente();
        frmModificarPaciente = new FrmModificarPaciente();
        frmEliminarPaciente = new FrmDeletePaciente();
        frmPaciente = new FrmPaciente();

        frmEliminarUsuario = new FrmEliminarUsuario();
        frmAgregarUsuario = new FrmAgregarUsuario();
        frmModificarUsuario = new FrmModificarUsuario();
        frmMostrarUsuario = new FrmJtable();

        initComponents();
        this.desktopPane.add(frmMedico);
        this.desktopPane.add(frmAgregarMedico);
        this.desktopPane.add(frmModificarMedico);
        this.desktopPane.add(frmBuscarMedico);
        this.desktopPane.add(frmEliminarMedico);

        this.desktopPane.add(frmEliminarPaciente);
        this.desktopPane.add(frmModificarPaciente);
        this.desktopPane.add(frmAgregarPaciente);
        this.desktopPane.add(frmBuscarPaciente);
        this.desktopPane.add(frmPaciente);

        this.desktopPane.add(frmEliminarUsuario);
        this.desktopPane.add(frmAgregarUsuario);
        this.desktopPane.add(frmModificarUsuario);
        this.desktopPane.add(frmMostrarUsuario);
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        desktopPane = new javax.swing.JDesktopPane();
        txtMedico = new javax.swing.JLabel();
        buttonMedico = new javax.swing.JButton();
        txtCitas = new javax.swing.JLabel();
        buttonCitas = new javax.swing.JButton();
        txtPaciente = new javax.swing.JLabel();
        buttonPacientes = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        buttonUsuarios = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMedicos = new javax.swing.JMenu();
        jMenuAgregar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuPacientes = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuCitas = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));
        desktopPane.setForeground(new java.awt.Color(255, 255, 255));

        txtMedico.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        txtMedico.setForeground(new java.awt.Color(255, 255, 255));
        txtMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMedico.setText("Medicos");
        desktopPane.add(txtMedico);
        txtMedico.setBounds(490, 300, 100, 30);

        buttonMedico.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        buttonMedico.setIcon(new javax.swing.ImageIcon("src\\main\\java\\com\\una\\citasmedicas\\image\\botonparamenu.jpg"));
        buttonMedico.setText("Medicos");
        buttonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicoActionPerformed(evt);
            }
        });
        desktopPane.add(buttonMedico);
        buttonMedico.setBounds(450, 290, 180, 60);

        txtCitas.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        txtCitas.setForeground(new java.awt.Color(255, 255, 255));
        txtCitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCitas.setText("Citas");
        desktopPane.add(txtCitas);
        txtCitas.setBounds(1260, 300, 100, 30);

        buttonCitas.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        buttonCitas.setIcon(new javax.swing.ImageIcon("src\\main\\java\\com\\una\\citasmedicas\\image\\botonparamenu.jpg"));
        buttonCitas.setText("Citas");
        buttonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCitasActionPerformed(evt);
            }
        });
        desktopPane.add(buttonCitas);
        buttonCitas.setBounds(1220, 290, 180, 60);

        txtPaciente.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        txtPaciente.setForeground(new java.awt.Color(255, 255, 255));
        txtPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPaciente.setText("Pacientes");
        desktopPane.add(txtPaciente);
        txtPaciente.setBounds(760, 300, 100, 30);

        buttonPacientes.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        buttonPacientes.setIcon(new javax.swing.ImageIcon("src\\main\\java\\com\\una\\citasmedicas\\image\\botonparamenu.jpg"));
        buttonPacientes.setText("Pacientes");
        buttonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPacientesActionPerformed(evt);
            }
        });
        desktopPane.add(buttonPacientes);
        buttonPacientes.setBounds(720, 290, 180, 60);

        txtUsuario.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUsuario.setText("Usuarios");
        desktopPane.add(txtUsuario);
        txtUsuario.setBounds(1000, 300, 100, 30);

        buttonUsuarios.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        buttonUsuarios.setIcon(new javax.swing.ImageIcon("src\\main\\java\\com\\una\\citasmedicas\\image\\botonparamenu.jpg"));
        buttonUsuarios.setText("Usuarios");
        buttonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsuariosActionPerformed(evt);
            }
        });
        desktopPane.add(buttonUsuarios);
        buttonUsuarios.setBounds(960, 290, 180, 60);

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Administración de modulos");
        desktopPane.add(jLabelTitulo);
        jLabelTitulo.setBounds(820, 180, 230, 50);

        jLabelFondo.setIcon(new javax.swing.ImageIcon("src\\main\\java\\com\\una\\citasmedicas\\image\\MdiWallpaper.jpg"));
        jLabelFondo.setText("jLabelfondo");
        desktopPane.add(jLabelFondo);
        jLabelFondo.setBounds(0, 10, 1940, 1010);

        jMenuMedicos.setText("Medicos");

        jMenuAgregar.setText("Agregar Medico");
        jMenuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarActionPerformed(evt);
            }
        });

        jMenuItem1.setText("ir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAgregar.add(jMenuItem1);

        jMenuMedicos.add(jMenuAgregar);

        jMenu2.setText("Buscar Medico");

        jMenuItem2.setText("Ir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuMedicos.add(jMenu2);

        jMenu3.setText("Modificar Medico");

        jMenuItem4.setText("Ir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuMedicos.add(jMenu3);

        jMenu4.setText("Eliminar Medico");

        jMenuItem5.setText("ir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuMedicos.add(jMenu4);

        jMenuBar1.add(jMenuMedicos);

        jMenuPacientes.setText("Pacientes");

        jMenu8.setText("Agregar Paciente");

        jMenuItem9.setText("Ir");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuPacientes.add(jMenu8);

        jMenu9.setText("Buscar Paciente");

        jMenuItem10.setText("Ir");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem10);

        jMenuPacientes.add(jMenu9);

        jMenu10.setText("Eliminar paciente");
        jMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu10ActionPerformed(evt);
            }
        });

        jMenuItem11.setText("Ir");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem11);

        jMenuPacientes.add(jMenu10);

        jMenu11.setText("Modificar Paciente");
        jMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu11ActionPerformed(evt);
            }
        });

        jMenuItem12.setText("Ir");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem12);

        jMenuPacientes.add(jMenu11);

        jMenuBar1.add(jMenuPacientes);

        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosActionPerformed(evt);
            }
        });

        jMenu1.setText("Agregar");

        jMenuItem6.setText("Ir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuUsuarios.add(jMenu1);

        jMenu5.setText("Eliminar");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Ir");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuUsuarios.add(jMenu5);

        jMenu6.setText("Modificar");

        jMenuItem7.setText("Ir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuUsuarios.add(jMenu6);

        jMenu7.setText("Mostrar");

        jMenuItem14.setText("Ir");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem14);

        jMenuUsuarios.add(jMenu7);

        jMenuBar1.add(jMenuUsuarios);

        jMenuCitas.setText("Citas");
        jMenuBar1.add(jMenuCitas);

        jMenuAbout.setText("About");
        jMenuBar1.add(jMenuAbout);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Aceptar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItem3);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed

    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        frmEliminarMedico.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmModificarMedico.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmBuscarMedico.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgregarActionPerformed

    }//GEN-LAST:event_jMenuAgregarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        frmAgregarMedico.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        frmAgregarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        frmEliminarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosActionPerformed

    }//GEN-LAST:event_jMenuUsuariosActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed

    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        frmModificarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        frmEliminarPaciente.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:

        frmAgregarPaciente.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        frmBuscarPaciente.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu10ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu10ActionPerformed

    private void jMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu11ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        frmModificarPaciente.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void buttonCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCitasActionPerformed

    private void buttonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicoActionPerformed
        // TODO add your handling code here:
        frmMedico.setVisible(true);
    }//GEN-LAST:event_buttonMedicoActionPerformed

    private void buttonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPacientesActionPerformed
        // TODO add your handling code here:
        frmPaciente.setVisible(true);
    }//GEN-LAST:event_buttonPacientesActionPerformed

    private void buttonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUsuariosActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        frmMostrarUsuario.setVisible(true);
        frmMostrarUsuario.mostrarTabla();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCitas;
    private javax.swing.JButton buttonMedico;
    private javax.swing.JButton buttonPacientes;
    private javax.swing.JButton buttonUsuarios;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenu jMenuAgregar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCitas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuMedicos;
    private javax.swing.JMenu jMenuPacientes;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel txtCitas;
    private javax.swing.JLabel txtMedico;
    private javax.swing.JLabel txtPaciente;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables

}
